import { Metadata } from "next"

export const metadata : Metadata = {
  title: {
    absolute: "This is learning Course",
    default: "Welcome to Next 14 Metadata",
    template: "%s | Prashant Dwivedi"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header 
          style={{
            backgroundColor: "lightblue",
            padding: "1rem"
          }}>
        <p>Header</p>
        </header>
        {children}
        <footer 
          style={{
           backgroundColor: "ghostwhite",
          padding: "1rem"
        }}>
        <p>footer</p>
        </footer>
      </body>
      
    </html>
  )
}
